### ISSUE TITLE
LEDs turning grey when switching between dashboard tabs

### ISSUE THREAD

**Issue by 3sztof** [Adorkable/node-red-contrib-ui-led#29]
The leds turn gray and do not change state after switching the UI tabs. Refreshing the whole UI turns them back on (it seems that the state is stored - it's a display issue).

**Comment by yoiang** [comment]
Thank you for the report @3sztof, I can reproduce this!

1. Cause an LED to change to a valid value
1. Switch to another dashboard tab
1. Switch back to the dashboard tab with the LED

LED will no longer be previous valid value but instead gray-invalid
Refreshing will show the LED's proper, valid value

**Comment by yoiang** [comment]
So I've narrowed it down to the node receiving the latest `msg` before it's element has been rendered, researching how to deal with this situation.

**Comment by yoiang** [comment]
I've pushed a fix to the branch https://github.com/Adorkable/node-red-contrib-ui-led/tree/feature/tabsUpdateBug , if you have a chance please give it a try and see if this fixes the issue for you without introducing new ones ;)

**Comment by yoiang** [comment]
Closing with fix release

**Comment by yoiang** [comment]
Oy, changes didn't make it into 0.2.2, my bad. They're in 0.2.3!

**Comment by darkoddio** [comment]
![image](https://user-images.githubusercontent.com/22075319/58460339-ba436080-812d-11e9-8aff-99c9fed1db21.png)
I'm already using 0.2.3, Node-red (in docker) v0.20.2
The issue still exist

**Comment by yoiang** [comment]
@darkoddio no worries! Can you paste a set of flows that demonstrate the issue?

**Comment by darkoddio** [comment]
`[{"id":"2f939364.d8796c","type":"ui_led","z":"cb054648.0d7a58","group":"9b7ac535.4c3aa8","order":0,"label":"","colorForValue":[{"color":"red","value":"false","valueType":"bool"},{"color":"green","value":"true","valueType":"bool"}],"name":"","x":290,"y":2660,"wires":[]},{"id":"9ac7d15.f6fe83","type":"ui_led","z":"cb054648.0d7a58","group":"407eebd8.3608e4","order":0,"label":"","colorForValue":[{"color":"red","value":"false","valueType":"bool"},{"color":"green","value":"true","valueType":"bool"}],"name":"","x":290,"y":2720,"wires":[]},{"id":"e498cee9.2287f","type":"debug","z":"cb054648.0d7a58","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":310,"y":2620,"wires":[]},{"id":"4988e325.f6e3cc","type":"debug","z":"cb054648.0d7a58","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":310,"y":2760,"wires":[]},{"id":"1fcbfb35.3d7535","type":"ui_switch","z":"cb054648.0d7a58","name":"","label":"switch","tooltip":"","group":"9b7ac535.4c3aa8","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":110,"y":2640,"wires":[["e498cee9.2287f","2f939364.d8796c"]]},{"id":"8913be8e.72efe","type":"ui_switch","z":"cb054648.0d7a58","name":"","label":"switch","tooltip":"","group":"407eebd8.3608e4","order":1,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":110,"y":2740,"wires":[["9ac7d15.f6fe83","4988e325.f6e3cc"]]},{"id":"9b7ac535.4c3aa8","type":"ui_group","z":"","name":"group1","tab":"365a841d.277acc","disp":true,"width":"6","collapse":false},{"id":"407eebd8.3608e4","type":"ui_group","z":"","name":"group2","tab":"3bad61f6.cc997e","disp":true,"width":"6","collapse":false},{"id":"365a841d.277acc","type":"ui_tab","z":"","name":"Tab1","icon":"dashboard","disabled":false,"hidden":false},{"id":"3bad61f6.cc997e","type":"ui_tab","z":"","name":"Tab2","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by yoiang** [comment]
@darkoddio I am unable to reproduce this issue with your pasted flow switching back and forth between tabs, are you sure you're on the latest release? This issue was addressed in 0.2.3.

Re: status display please post suggestions in #6!
